# [".slimzsh"]
#    type = "git-repo"
#    url = "https://github.com/changs/slimzsh.git"
#    refreshPeriod = "168h"

[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/ericreeves/lazyvim"
    refreshPeriod = "1h"

[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "1h"

#[".oh-my-zsh"]
#    type = "archive"
#    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
#    exact = true
#    stripComponents = 1
#    refreshPeriod = "168h"

[".local/share/fonts/"]
type = "archive"
include = ["*.ttf"]
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz"

[".local/share/fonts/./"]
type = "archive"
include = ["*.ttf"]
url = "https://github.com/mietzen/juliamono-nerd-font/releases/download/v0.059/fonts.zip"
