[".slimzsh"]
    type = "git-repo"
    url = "https://github.com/changs/slimzsh.git"
    refreshPeriod = "168h"

[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/ericreeves/NormalNvim.git"
    refreshPeriod = "1h"
