[".slimzsh"]
    type = "git-repo"
    url = "https://github.com/changs/slimzsh.git"
    refreshPeriod = "168h"

# [".config/nvim"]
#     type = "git-repo"
#     url = "https://github.com/ericreeves/NormalNvim.git"
#     refreshPeriod = "1h"

#[".oh-my-zsh"]
#    type = "archive"
#    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
#    exact = true
#    stripComponents = 1
#    refreshPeriod = "168h"
