# Swap Ctrl-B for Ctrl-W
set-option -g prefix C-w
unbind-key C-b
bind-key C-w send-prefix

# Make Ctrl-W twice switch windows
bind-key C-w last-window

# Escape == copy mode
bind-key '`' copy-mode

# Don't wait for escape codes, just GO
set -s escape-time 0

# Pane display
bind C-r display-panes
set-option -g display-panes-time 2000

# VI keys for moving between panes and windows
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

# Pane resizing, EDSF
bind C-s resize-pane -L 4
bind C-f resize-pane -R 4
bind C-d resize-pane -D 4
bind C-e resize-pane -U 4

# Binding to reload the config
bind r source-file ~/.tmux.conf

# Make the status bar white on blue
set-option -g status-bg blue
set-option -g status-fg white

# Logical Window Splitting (- and | to split vertically and horizontally)
unbind %
bind | split-window -h
bind - split-window -v

# Set Pane Border Colors
set-option -g pane-active-border-bg black
set-option -g pane-active-border-fg blue
set-option -g pane-border-bg black
set-option -g pane-border-fg white

# Start window indexing at...
set -g base-index 0

# VI keys for tmux copy mode
set-option status-keys vi
set-window-option -g mode-keys vi
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection

# Mouse settings
#set-option -g mouse-select-pane on
#set-option -g mouse-select-window on
#set-option -g mouse-resize-pane on
#set-option -g mouse-utf8 on
set-window-option -g mode-mouse off

# Set default 256-color terminal
set -g default-terminal "xterm-256color"

#### Status Bar ####
set -g status-interval 1
set -g status-justify centre # center align window list
set -g status-left-length 25 
set -g status-left '#[fg=black,bright][ #[fg=white]#H#[fg=black,bright]/#[fg=white]#S #[fg=black,bright]] #[default]'
set -g status-right-length 60 
set -g status-right '#[fg=black,bright][ #[fg=white]#(date | cut -c 1-19) #[fg=black,bright]]#[default]'

# Default Status Bar Colors
set -g status-fg white
set -g status-bg blue 
set -g status-attr bright

# default window title colors
set-window-option -g window-status-fg white
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg white 
set-window-option -g window-status-current-bg black
set-window-option -g window-status-current-attr dim

# command/message line colors
set -g message-fg white
set -g message-bg black
set -g message-attr bright

set -g default-terminal "screen-256color"

bind-key @ command-prompt -p "create pane from:"  "join-pane -s ':%%'"

bind C-q setw synchronize-panes

# for smux
new-session -s main
