[Unit]
Name = "desktop"
Description = "Everything I need to work on Windows"
Requires = ["komorebi", "kanata", "yasb", "whkd"]

[Service]
Kind = "Oneshot"
Autostart = true
Restart = "Never"

[Service.ExecStart]
Executable = "rundll32" # An exe that does nothing apparently (when given no args)
