[Unit]
Name = "desktop"
Description = "Desktop WPM-managed Services"
Requires = [
    "whkd",
    "altsnap",
    "rawaccel",
]

[Service]
Kind = "Simple"
Autostart = true
Restart = "Never"

[Service.ExecStart]
Executable = "cmd.exe"
Arguments = ["/c", "pause"]
