[Unit]
Name = "komorebi"
Description = "Tiling window management for Windows"

[Service]
Kind = "Forking"
Restart = "Always"
RestartSec = 2

[Service.ExecStart]
Executable = "komorebic.exe"
Arguments = ["start"]
Environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]

[[Service.ExecStop]]
Executable = "komorebic.exe"
Arguments = ["stop"]

[[Service.ExecStopPost]]
Executable = "komorebic.exe"
Arguments = ["restore-windows"]

[Service.Healthcheck.Process]
Target = "komorebi.exe"
DelaySec = 1
