[Unit]
Name = "masir"
Description = "Focus follows mouse for Windows"

[Service]
Restart = "OnFailure"
RestartSec = 2
#Autostart = true # Started by desktop

[Service.ExecStart]
Executable = "masir.exe"

[Service.Healthcheck.Process]
DelaySec = 1
