[Unit]
Name = "whkd"
Description = "Simple hotkey daemon for Windows"

[Service]
Kind = "Simple"
Restart = "OnFailure"
RestartSec = 2

[Service.ExecStart]
Executable = "whkd.exe"
Arguments = [
    "--config",
    "$USERPROFILE/.config/komorebi/whkdrc",
]
Environment = [[
    "WHKD_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]


[Service.Healthcheck.Process]
DelaySec = 1
