#!/bin/bash

# Central colorscheme — single source of truth
# All tools (sketchybar, borders, etc.) source this file
# iOS dark theme inspired by komorebi-bar

export COLOR_BG="1c1c1e"
export COLOR_BG_SECONDARY="2c2c2e"
export COLOR_BG_TERTIARY="3a3a3c"
export COLOR_FG="ebebf5"
export COLOR_FG_SECONDARY="f2f2f7"
export COLOR_SUBTLE="636366"
export COLOR_INACTIVE="48484a"
export COLOR_ACCENT="e0e0e4"
export COLOR_RED="ff453a"
export COLOR_ORANGE="ff9f0a"
export COLOR_YELLOW="ffd60a"
export COLOR_GREEN="30d158"
export COLOR_BLUE="64d2ff"
export COLOR_PURPLE="bf5af2"
export COLOR_PINK="ff375f"
export COLOR_LAVENDER="b4befe"

# Catppuccin Mocha palette (used for border state colors)
export CATPPUCCIN_ROSEWATER="f5e0dc"
export CATPPUCCIN_FLAMINGO="f2cdcd"
export CATPPUCCIN_PINK="f5c2e7"
export CATPPUCCIN_MAUVE="cba6f7"
export CATPPUCCIN_RED="f38ba8"
export CATPPUCCIN_MAROON="eba0ac"
export CATPPUCCIN_PEACH="fab387"
export CATPPUCCIN_YELLOW="f9e2af"
export CATPPUCCIN_GREEN="a6e3a1"
export CATPPUCCIN_TEAL="94e2d5"
export CATPPUCCIN_SKY="89dceb"
export CATPPUCCIN_SAPPHIRE="74c7ec"
export CATPPUCCIN_BLUE="89b4fa"
export CATPPUCCIN_LAVENDER="b4befe"
export CATPPUCCIN_TEXT="cdd6f4"
export CATPPUCCIN_SUBTEXT1="bac2de"
export CATPPUCCIN_SUBTEXT0="a6adc8"
export CATPPUCCIN_OVERLAY2="9399b2"
export CATPPUCCIN_OVERLAY1="7f849c"
export CATPPUCCIN_OVERLAY0="6c7086"
export CATPPUCCIN_SURFACE2="585b70"
export CATPPUCCIN_SURFACE1="45475a"
export CATPPUCCIN_SURFACE0="313244"
export CATPPUCCIN_BASE="1e1e2e"
export CATPPUCCIN_MANTLE="181825"
export CATPPUCCIN_CRUST="11111b"
